(function(){
const C=window.CAREERLAB_CONFIG||{},ENDPOINT=C.AI_ENDPOINT||"";let supa=null,session=null,profile=null,config=null;
const $=id=>document.getElementById(id); const visitorId=localStorage.getItem("careerlab_visitor_id")||crypto.randomUUID(); localStorage.setItem("careerlab_visitor_id",visitorId); const esc=x=>String(x||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
async function getToken(){if(!supa)return null;const r=await supa.auth.getSession();session=r.data.session;return session?.access_token||null}
window.careerLabGetAccessToken=getToken;
async function api(path,opts={}){const t=await getToken(),h={"Content-Type":"application/json","X-CareerLab-Visitor":visitorId,...(opts.headers||{})};if(t)h.Authorization="Bearer "+t;const r=await fetch(ENDPOINT+path,{...opts,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||d.detail||"Request failed");return d}
function toast(text){const el=$("unlockToast");if(!el)return;$("unlockText").textContent=text;el.classList.remove("hidden");clearTimeout(window.__clToast);window.__clToast=setTimeout(()=>el.classList.add("hidden"),4200)}
window.careerLabUnlock=label=>toast(label+" is ready for you.");
function signedOut(){const a=$("accountArea");if(a)a.innerHTML='<a class="account-btn" href="auth.html">Sign in</a>';$("planBadge")?.classList.add("hidden");updateJourney(false)}
function signedIn(user,p){const a=$("accountArea");if(!a)return;const name=p?.display_name||user.user_metadata?.display_name||user.email?.split("@")[0]||"Account";a.innerHTML=`<div class="account-user"><span class="account-avatar">${esc(name[0].toUpperCase())}</span><span>${esc(name)}</span></div><button id="signOutBtn" class="account-menu-btn">Sign out</button>`;$("signOutBtn").onclick=async()=>{await supa.auth.signOut();location.href="index.html"};updateJourney(true)}
function applyConfig(c){config=c||{};const enabled=!!config.plansEnabled;document.querySelector("#plansSection")?.classList.toggle("hidden",!enabled);const b=$("planBadge");if(enabled){b.classList.remove("hidden");b.textContent=profile?.plan==="pro"?"PRO":"FREE";b.className=profile?.plan==="pro"?"plan pro":"plan free";$("proPrice").textContent="₹"+Math.round((config.proPrice||49900)/100);$("freeList").innerHTML=(config.planCopy?.free||["Resume analysis","Basic Explorer","Limited practice"]).map(x=>`<li>${esc(x)}</li>`).join("");$("proList").innerHTML=(config.planCopy?.pro||["Advanced interview coaching","Higher usage limits","Personalized learning","Job discovery"]).map(x=>`<li>${esc(x)}</li>`).join("");}else b?.classList.add("hidden")}
function updateJourney(isSigned){const title=$("nextStepTitle"),text=$("nextStepText"),btn=$("nextStepBtn");if(!title)return;if(!isSigned){title.textContent="Explore first. Sign in when you want to keep going.";text.textContent="Your visitor trial is limited. Sign in to save your journey and continue with your free allowance.";btn.textContent="Create free account";btn.href="auth.html"}else if(profile?.plan==="pro"){title.textContent="Your Pro journey is active.";text.textContent="Continue learning, practicing and tracking your progress.";btn.textContent="Go to your account";btn.href="auth.html"}else{title.textContent="Keep learning with your free account.";text.textContent="Use your enabled free features. When you reach a Pro feature or limit, CareerLab will explain why and show the secure upgrade path.";btn.textContent="Open account";btn.href="auth.html"}}
function openGate(message,needLogin=true){$("upgradeMessage").textContent=message;$("modalPrimary").textContent=needLogin?"Sign in / Create account":"See Pro options";$("upgradeModal").classList.remove("hidden");window.__gateLogin=needLogin}
async function canUse(feature,requireAction=false){try{const d=await api("/usage/check",{method:"POST",body:JSON.stringify({feature,consume:!!requireAction})});if(d.allowed)return true;openGate(d.message||"You have reached the current access limit.",!session);return false}catch(e){if(!session){openGate("Sign in to continue this part of CareerLab.",true);return false}console.warn(e.message);return true}}
window.careerLabCanUse=canUse;
window.careerLabRequireLogin=()=>{if(session)return true;location.href="auth.html?next="+encodeURIComponent(location.href);return false};
window.careerLabSetPlan=plan=>{if(profile)profile.plan=plan;applyConfig(config);};
window.careerLabStartPayment=async()=>{if(!session){window.careerLabRequireLogin();return}if(!config?.plansEnabled){toast("Secure Pro checkout is not enabled yet.");return}const status=$("upgradeMessage");try{status.textContent="Creating a secure payment order…";$("upgradeModal").classList.remove("hidden");const o=await api("/payment/order",{method:"POST",body:JSON.stringify({plan:"pro"})});const rz=new Razorpay({key:o.key_id,amount:o.amount,currency:o.currency,name:"CareerLab",description:"CareerLab Pro",order_id:o.order_id,prefill:{email:session.user.email,name:profile?.display_name||"",contact:profile?.phone||""},theme:{color:"#5b5cf6"},handler:async response=>{try{status.textContent="Payment received. CareerLab is securely verifying it…";const v=await api("/payment/verify",{method:"POST",body:JSON.stringify(response)});if(v.ok){profile.plan="pro";applyConfig(config);toast("Pro access unlocked after payment verification.");status.textContent="Payment verified. Your Pro access is active. Receipt delivery has been requested to your registered email/phone.";setTimeout(()=>$("upgradeModal").classList.add("hidden"),2600)}}catch(e){status.textContent="Payment was not activated because server verification failed. No Pro access was granted.";console.error(e)}}});rz.open()}catch(e){status.textContent=e.message}}
async function sync(){if(!session){profile=null;signedOut();return}try{const d=await api("/me");profile=d.profile;config=d.config;applyConfig(config);signedIn(d.user,d.profile)}catch(e){signedIn(session.user,null)}}
async function init(){if(!window.supabase||!C.SUPABASE_URL||!C.SUPABASE_PUBLISHABLE_KEY){signedOut();try{config=await api("/config");applyConfig(config)}catch{}return}supa=window.supabase.createClient(C.SUPABASE_URL,C.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});const s=await supa.auth.getSession();session=s.data.session;await sync();try{if(!config){config=await api("/config");applyConfig(config)}}catch{}supa.auth.onAuthStateChange(async(_e,sess)=>{session=sess;await sync()})}
init();
})();
