const C=window.CAREERLAB_CONFIG||{};
const AI_ENDPOINT=C.AI_ENDPOINT||"";
const DOMAINS=["ServiceNow","Software Engineering","Frontend Development","Backend Development","Full Stack Development","Mobile Development","Java","Python","JavaScript / TypeScript","Data Structures & Algorithms","Data Engineering","Data Science","Artificial Intelligence / Machine Learning","Generative AI","Cloud / AWS","Microsoft Azure","Google Cloud","DevOps","SRE","Cybersecurity","Networking","Database / SQL","API / Integration","System Design","Solution Architecture","IT Support","IT Operations","ITSM","CRM","SAP","Salesforce","Testing / QA","Business Analysis","Product Management","Project Management","Operations","Supply Chain","Finance","Accounting","Banking","Marketing","Human Resources","Healthcare","Legal","Education","Manufacturing","Other IT","Other Non-IT","Custom"];
const $=id=>document.getElementById(id); const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
const redact=x=>String(x||"").replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,"[EMAIL]").replace(/\b(?:\+?\d[\d\s().-]{8,}\d)\b/g,"[PHONE]");
const state={resumeText:"",domain:"ServiceNow",analysis:null,skills:[],interview:{running:false,question:"",turns:[],type:"Resume Interview",difficulty:"Medium"}};
async function api(body){const token=await window.careerLabGetAccessToken?.();const h={"Content-Type":"application/json"};if(token)h.Authorization="Bearer "+token;const r=await fetch(AI_ENDPOINT,{method:"POST",headers:h,body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||d.error||"CareerLab AI request failed");return d;}
function parseJson(text){try{return JSON.parse(text)}catch{}const m=String(text||"").match(/\{[\s\S]*\}/);if(!m)return null;try{return JSON.parse(m[0])}catch{return null}}
async function pdfText(file){const pdfjs=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");pdfjs.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";const pdf=await pdfjs.getDocument({data:await file.arrayBuffer()}).promise;const pages=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i);const content=await page.getTextContent();pages.push(content.items.map(x=>x.str).join(" "));}return pages.join("\n").slice(0,36000)}
async function docxText(file){if(!window.mammoth)throw new Error("DOCX reader is not loaded yet.");const result=await window.mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return result.value.slice(0,36000)}
async function loadResume(file){if(!file)return;if(file.size>8*1024*1024)throw new Error("Maximum resume size is 8 MB.");$("fileStatus").innerHTML="<span class='dot'></span>Reading resume locally…";let text="";if(file.name.toLowerCase().endsWith(".pdf"))text=await pdfText(file);else if(file.name.toLowerCase().endsWith(".docx"))text=await docxText(file);else throw new Error("Please upload a PDF or DOCX file.");if(text.trim().length<120)throw new Error("The resume text could not be read. Try a text-based PDF or DOCX.");state.resumeText=text;localStorage.setItem("careerlab_resume_loaded","1");$("fileStatus").innerHTML=`<span class='dot'></span>${esc(file.name)} · browser memory only`;window.careerLabUnlock?.("Resume analysis");}
function resetResumeUI(){state.resumeText="";state.analysis=null;state.skills=[];$("fileStatus").innerHTML="<span class='dot'></span>No resume loaded";$("score").textContent="—";$("scorebar").style.width="0%";$("scoreReason").textContent="Upload a resume to generate analysis.";$("analysisSummary").textContent="Your resume-specific analysis will appear here.";$("skillMap").className="skillmap empty";$("skillMap").textContent="Your supported skills, evidence warnings and interview areas will appear here.";$("learningGrid").innerHTML='<div class="learning-empty">Analyze your resume to build a personalized Learning Lab.</div>';}
function formatAnswer(raw){let s=String(raw||"").replace(/```(?:markdown|text)?/gi,"").replace(/```/g,"");s=s.replace(/^\s*\*{1,3}\s*/gm,"• ").replace(/^\s*#{1,6}\s*/gm,"");s=s.replace(/\*\*(.*?)\*\*/g,"$1").replace(/\*(.*?)\*/g,"$1");s=s.replace(/^\s*[-•]\s+/gm,"• ");return s.trim();}
function renderAnalysis(j){const score=Math.max(0,Math.min(100,Number(j.score)||0));$("score").textContent=score+"/100";$("scorebar").style.width=score+"%";$("scoreReason").textContent=j.summary||j.scoreReason||"CareerLab has completed the current resume assessment.";const strengths=Array.isArray(j.strengths)?j.strengths:[],gaps=Array.isArray(j.gaps)?j.gaps:[];$("analysisSummary").innerHTML=`<div class="careerlab-callout"><strong>CareerLab Guidance</strong><span>This guidance is generated from the resume you provided.</span></div><h3>What your resume supports</h3><ul>${strengths.map(x=>`<li>${esc(x)}</li>`).join("")||"<li>No strong evidence was identified yet.</li>"}</ul><h3>What to strengthen or verify</h3><ul>${gaps.map(x=>`<li>${esc(x)}</li>`).join("")||"<li>No major gap was identified by the current analysis.</li>"}</ul>`;const tags=[...new Set([...(Array.isArray(j.skills)?j.skills:[]),...(Array.isArray(j.interviewAreas)?j.interviewAreas:[])])];state.skills=Array.isArray(j.skills)?j.skills:[];$("skillMap").className="skillmap";$("skillMap").innerHTML=tags.length?tags.map(x=>`<span class="skill">${esc(x)}</span>`).join(""):"No supported skills detected yet.";renderLearningLab();updateJobDefaults();}
async function analyze(){if(!state.resumeText)return alert("Upload your resume first.");if(!(await window.careerLabCanUse?.("resume_analysis",true)))return;$("analyzeBtn").disabled=true;$("analyzeBtn").textContent="Analyzing…";try{const d=await api({mode:"resume_analysis",domain:state.domain,resumeText:redact(state.resumeText)});const j=d.analysis||parseJson(d.answer)||{};state.analysis=j;renderAnalysis(j);window.careerLabUnlock?.("Personalized resume insights");}catch(e){$("analysisSummary").textContent="CareerLab could not complete the analysis: "+e.message;}finally{$("analyzeBtn").disabled=false;$("analyzeBtn").textContent="Analyze My Resume";}}
async function explore(modeOverride){if(!state.resumeText)return alert("Upload and analyze your resume first.");const mode=modeOverride||$("exploreMode").value;if(!(await window.careerLabCanUse?.(mode==="project"?"project_architecture":"explorer",true)))return;try{$("exploreOutput").textContent="CareerLab is preparing your answer…";const d=await api({mode,resumeText:redact(state.resumeText),domain:state.domain,topic:$("exploreTopic").value,question:$("exploreQuestion").value});$("exploreOutput").textContent=formatAnswer(d.answer||"No answer returned.");}catch(e){$("exploreOutput").textContent="CareerLab could not answer this yet. "+e.message;}}
async function startInterview(){if(!state.resumeText)return alert("Upload and analyze your resume first.");if(!(await window.careerLabCanUse?.("mock_interview",true)))return;state.interview={running:true,question:"",turns:[],type:$("interviewType").value,difficulty:$("difficulty").value};$("chat").innerHTML="";$("interviewState").textContent="Interview in progress";await nextInterview("Start with one focused question.");}
async function nextInterview(instruction){try{const d=await api({mode:"mock_interview",resumeText:redact(state.resumeText),domain:state.domain,interviewType:state.interview.type,difficulty:state.interview.difficulty,history:state.interview.turns,instruction});state.interview.question=formatAnswer(d.answer||"Tell me about one project on your resume.");$("chat").insertAdjacentHTML("beforeend",`<div class="msg ai"><span class="msg-label">CareerLab</span>${esc(state.interview.question)}</div>`);$("chat").scrollTop=$("chat").scrollHeight;}catch(e){$("chat").insertAdjacentHTML("beforeend",`<div class="msg ai">CareerLab could not continue: ${esc(e.message)}</div>`);}}
async function evaluateInterviewAnswer(answer){try{const d=await api({mode:"interview_feedback",resumeText:redact(state.resumeText),domain:state.domain,question:state.interview.question,answer});$("sampleAnswer").textContent=formatAnswer(d.answer||"No guidance returned.");}catch(e){$("sampleAnswer").textContent="CareerLab could not evaluate the answer yet. "+e.message;}}
async function answerInterview(){const answer=$("answerInput").value.trim();if(!answer||!state.interview.running)return;if(!(await window.careerLabCanUse?.("mock_interview_answer",true)))return;$("chat").insertAdjacentHTML("beforeend",`<div class="msg user"><span class="msg-label">You</span>${esc(answer)}</div>`);state.interview.turns.push({question:state.interview.question,answer});$("answerInput").value="";await evaluateInterviewAnswer(answer);await nextInterview("Briefly evaluate the previous answer, then ask one focused follow-up question. If the answer claims unsupported experience, ask the candidate to verify it.");}
function stopInterview(){state.interview.running=false;$("interviewState").textContent="Interview ended.";}
function renderLearningLab(){const grid=$("learningGrid");if(!grid)return;if(!state.analysis){grid.innerHTML='<div class="learning-empty">Analyze your resume to build a personalized Learning Lab.</div>';return}const a=state.analysis;const topics=[...(Array.isArray(a.learningPath)?a.learningPath:[]),...(Array.isArray(a.gaps)?a.gaps:[]),...(Array.isArray(a.interviewAreas)?a.interviewAreas:[])].map(x=>String(x||"").trim()).filter(Boolean);const unique=[...new Set(topics)].slice(0,15);if(!unique.length){grid.innerHTML='<div class="learning-empty">CareerLab did not find enough resume-specific evidence to build topics yet.</div>';return}grid.innerHTML=unique.map((t,i)=>`<article class="learn-card"><span class="eyebrow">${i<4?"RECOMMENDED":"INTERVIEW PRACTICE"}</span><h3>${esc(t)}</h3><p>Personalized from your resume evidence, gaps and interview areas.</p><button class="secondary learn-btn" data-topic="${esc(t)}">Learn & Practice →</button></article>`).join("");grid.querySelectorAll(".learn-btn").forEach(b=>b.onclick=()=>{$("exploreTopic").value=b.dataset.topic;$("exploreQuestion").value=`Teach me ${b.dataset.topic} in a practical interview-ready way based on my resume.`;document.getElementById("explorer").scrollIntoView({behavior:"smooth"});});}
function updateJobDefaults(){$("jobKeyword").value=state.skills.slice(0,2).join(" ")||state.domain;}
function buildJobLinks(keyword,location){const title=encodeURIComponent(keyword),loc=encodeURIComponent(location||""),q=encodeURIComponent(`${keyword} ${location}`.trim()),slug=(keyword||state.domain).toLowerCase().replace(/[^a-z0-9]+/g,"-");return[{name:"LinkedIn Jobs",url:`https://www.linkedin.com/jobs/search/?keywords=${title}&location=${loc}`},{name:"Indeed",url:`https://www.indeed.com/jobs?q=${q}`},{name:"Google Jobs",url:`https://www.google.com/search?q=${q}+jobs`},{name:"Glassdoor",url:`https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=${title}`},{name:"Naukri",url:`https://www.naukri.com/${slug}-jobs`}];}
function searchJobs(){const keyword=$("jobKeyword").value.trim()||state.skills.slice(0,2).join(" ")||state.domain,location=$("jobLocation").value.trim();const jobs=buildJobLinks(keyword,location);$("jobResults").innerHTML=jobs.map(j=>`<div class="job-card"><div><h3>${esc(j.name)}</h3><p>Search ${esc(keyword)} ${location?`in ${esc(location)}`:""} using your CareerLab profile.</p></div><a class="primary" href="${esc(j.url)}" target="_blank" rel="noopener noreferrer">Search Jobs ↗</a></div>`).join("");}
function speechSetup(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("voiceBtn").disabled=true;$("voiceStatus").textContent="Voice input is not supported by this browser.";return}let rec=null;$("voiceBtn").onclick=()=>{if(rec){rec.stop();return}rec=new SR();rec.lang="en-IN";rec.interimResults=true;rec.continuous=false;rec.onstart=()=>{$("voiceBtn").textContent="⏹️ Stop speaking";$("voiceStatus").textContent="Listening in English…"};rec.onresult=e=>{let finalText="";for(const r of e.results)finalText+=r[0].transcript+" ";$("answerInput").value=(($("answerInput").value||"")+" "+finalText).trim()};rec.onerror=e=>{$("voiceStatus").textContent="Voice input error: "+e.error};rec.onend=()=>{$("voiceBtn").textContent="🎙️ Speak Answer";$("voiceStatus").textContent="English only";rec=null};rec.start()};}
function modeButtons(){const saved=localStorage.getItem("careerlab_reading")==="1",night=localStorage.getItem("careerlab_night")==="1";document.body.classList.toggle("reading-mode",saved);document.body.classList.toggle("night-mode",night);$("readingBtn").onclick=()=>{document.body.classList.toggle("reading-mode");localStorage.setItem("careerlab_reading",document.body.classList.contains("reading-mode")?"1":"0")};$("nightBtn").onclick=()=>{document.body.classList.toggle("night-mode");localStorage.setItem("careerlab_night",document.body.classList.contains("night-mode")?"1":"0")};}
function init(){modeButtons();speechSetup();$("careerDomain").innerHTML=DOMAINS.map(d=>`<option>${esc(d)}</option>`).join("");$("careerDomain").value=state.domain;$("resumeFile").onchange=async e=>{try{await loadResume(e.target.files[0])}catch(err){alert(err.message)}};$("deleteBtn").onclick=resetResumeUI;$("analyzeBtn").onclick=analyze;$("exploreBtn").onclick=()=>explore();$("architectureBtn").onclick=()=>explore("project");$("clearOutputBtn").onclick=()=>$("exploreOutput").textContent="Upload a resume and ask a question.";$("startInterview").onclick=startInterview;$("stopInterview").onclick=stopInterview;$("answerBtn").onclick=answerInterview;$("jobSearchBtn").onclick=searchJobs;$("tryNowBtn").onclick=()=>document.getElementById("explorer").scrollIntoView({behavior:"smooth"});$("careerDomain").onchange=e=>state.domain=e.target.value;$("closeModal").onclick=()=>$("upgradeModal").classList.add("hidden");$("modalSecondary").onclick=()=>$("upgradeModal").classList.add("hidden");$("modalPrimary").onclick=()=>{if(window.careerLabRequireLogin?.())$("upgradeModal").classList.add("hidden")};$("pricingUpgradeBtn").onclick=()=>window.careerLabStartPayment?.();}
window.addEventListener("DOMContentLoaded",init);
