/* CareerLab v2 — browser-only resume state. Replace this URL after deploying the Worker. */
const AI_ENDPOINT="https://YOUR-WORKER.workers.dev";
let s={fileName:"",resumeText:"",skills:[],domain:"ServiceNow",interview:{running:false,type:"",q:"",turns:[]}};
const $=id=>document.getElementById(id), domains=["ServiceNow","Software Engineering","Cloud / AWS","DevOps","Java","Python","Data / AI","Cybersecurity","Frontend / Web","Backend / APIs","ITSM / IT Operations","Custom"], topics=["Incident Management","Problem Management","Change Management","Release Management","CMDB","CSDM","REST Integration","Flow Designer","Business Rules","Client Scripts","Virtual Agent","Now Assist / AI","ITOM","Service Catalog"];
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const redact=x=>String(x||"").replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,"[EMAIL]").replace(/\b(?:\+?\d[\d\s().-]{8,}\d)\b/g,"[PHONE]");
async function api(body){if(AI_ENDPOINT.includes("YOUR-WORKER"))throw Error("Deploy the Worker first, then replace AI_ENDPOINT in app.js.");let r=await fetch(AI_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"AI request failed");return d}
async function pdfText(file){const p=await import("https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.min.mjs");p.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.10.38/pdf.worker.min.mjs";const pdf=await p.getDocument({data:await file.arrayBuffer()}).promise,o=[];for(let i=1;i<=pdf.numPages;i++){let pg=await pdf.getPage(i),c=await pg.getTextContent();o.push(c.items.map(x=>x.str).join(" "))}return o.join("\n")}
async function docxText(file){let r=await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()});return r.value}
async function load(file){if(!file)return;$('fileStatus').textContent="Reading resume locally…";try{let t=file.name.toLowerCase().endsWith('.pdf')?await pdfText(file):await docxText(file);t=t.replace(/\u0000/g,'').slice(0,30000).trim();if(t.length<80)throw Error("Not enough readable text. Try a text-based PDF/DOCX.");s.fileName=file.name;s.resumeText=t;$('fileStatus').innerHTML='<i class="dot"></i>'+esc(file.name)+' · browser memory only';$('analysisSummary').textContent="Resume loaded. Click Analyze with AI."}catch(e){$('fileStatus').textContent="⚠️ "+e.message}}
function reset(){s={fileName:"",resumeText:"",skills:[],domain:$('careerDomain')?.value||"ServiceNow",interview:{running:false,type:"",q:"",turns:[]}};$('resumeFile').value="";$('fileStatus').innerHTML='<i class="dot"></i>No resume loaded';$('score').textContent="—";$('scorebar').style.width="0";$('scoreReason').textContent="Upload a resume to generate analysis.";$('analysisSummary').textContent="Your resume-specific results will appear here.";$('skillMap').textContent="Your skills and likely interview areas will appear here.";$('exploreOutput').textContent="Upload a resume and ask a question.";$('chat').innerHTML='<div class="msg ai">Start a mock interview and I will ask one question at a time.</div>';$('interviewState').textContent="No interview running.";$('diagramText').textContent="Ask CareerLab to generate a Mermaid flow/sequence diagram."}
function jsonText(t){try{return JSON.parse(t)}catch{}let m=String(t).match(/\{[\s\S]*\}/);try{return m?JSON.parse(m[0]):null}catch{return null}}
async function analyze(){if(!s.resumeText)return alert("Upload a resume first.");$('analysisSummary').textContent="Analyzing…";try{let d=await api({mode:'resume_analysis',domain:s.domain,resumeText:redact(s.resumeText)}),j=jsonText(d.answer)||{};s.skills=Array.isArray(j.skills)?j.skills:[];$('score').textContent=(Number(j.score)||0)+"/100";$('scorebar').style.width=Math.max(0,Math.min(100,Number(j.score)||0))+"%";$('scoreReason').textContent=j.summary||"Analysis completed.";$('analysisSummary').textContent=[j.strengths?.length?"Strengths:\n• "+j.strengths.join("\n• "):"",j.gaps?.length?"Gaps:\n• "+j.gaps.join("\n• "):"",j.evidenceWarnings?.length?"Evidence warnings:\n• "+j.evidenceWarnings.join("\n• "):""].filter(Boolean).join("\n\n")||d.answer;$('skillMap').innerHTML=s.skills.map(x=>`<span class="skill">${esc(x)}</span>`).join("")}catch(e){$('analysisSummary').textContent="⚠️ "+e.message}}
async function explore(){if(!s.resumeText)return alert("Upload a resume first.");$('exploreOutput').textContent="Thinking…";let mode=$('exploreMode').value;try{let d=await api({mode,resumeText:redact(s.resumeText),domain:s.domain,topic:$('exploreTopic').value,question:$('exploreQuestion').value,skills:s.skills});$('exploreOutput').textContent=d.answer||"No answer.";let m=String(d.answer||'').match(/```mermaid\s*([\s\S]*?)```/i);if(m)$('diagramText').textContent=m[1].trim()}catch(e){$('exploreOutput').textContent="⚠️ "+e.message}}
async function start(){if(!s.resumeText)return alert("Upload a resume first.");s.interview={running:true,type:$('interviewType').value,q:"",turns:[]};$('chat').innerHTML="";$('interviewState').textContent="Interview running · resume evidence only";await next("Start the interview. Ask one realistic question based on the resume.")}
async function next(instruction){try{let d=await api({mode:'mock_interview',resumeText:redact(s.resumeText),domain:s.domain,interviewType:s.interview.type,history:s.interview.turns,instruction});s.interview.q=d.answer||"Tell me about one project on your resume.";$('chat').insertAdjacentHTML('beforeend',`<div class="msg ai">${esc(s.interview.q)}</div>`);$('chat').scrollTop=$('chat').scrollHeight}catch(e){$('chat').insertAdjacentHTML('beforeend',`<div class="msg ai">⚠️ ${esc(e.message)}</div>`)} }
async function answer(){let a=$('answerInput').value.trim();if(!a||!s.interview.running)return;$('chat').insertAdjacentHTML('beforeend',`<div class="msg user">${esc(a)}</div>`);s.interview.turns.push({question:s.interview.q,answer:a});$('answerInput').value="";await next("Briefly evaluate the answer, then ask one focused follow-up. Do not invent missing experience.")}
$('resumeFile').onchange=e=>load(e.target.files[0]);$('deleteBtn').onclick=()=>confirm("Delete this resume session now?")&&reset();$('analyzeBtn').onclick=analyze;$('exploreBtn').onclick=explore;$('startInterview').onclick=start;$('answerBtn').onclick=answer;$('answerInput').onkeydown=e=>e.key==='Enter'&&answer();
$('careerDomain').innerHTML=domains.map(x=>`<option>${x}</option>`).join("");$('careerDomain').onchange=e=>s.domain=e.target.value;
$('learningGrid').innerHTML=topics.map(t=>`<div class="card"><h3>${esc(t)}</h3><p class="muted">Purpose · real example · common mistakes · practical flow · interview explanation · follow-up questions.</p><button data-t="${esc(t)}">Understand →</button></div>`).join("");document.querySelectorAll('#learningGrid button').forEach(b=>b.onclick=()=>{$('exploreMode').value='experience';$('exploreTopic').value=b.dataset.t;$('exploreQuestion').value='Teach me this for an interview. Separate general knowledge from what my resume proves.';document.querySelector('#explorer').scrollIntoView({behavior:'smooth'});explore()});
fetch('sources.json').then(r=>r.json()).then(x=>$('sourceList').innerHTML=x.official.map(a=>`<a href="${a[1]}" target="_blank" rel="noopener">${esc(a[0])}</a>`).join('')).catch(()=>{});reset();
