/* Run from the CareerLab repo root with: node apply-patch.js
   This patches the current frontend without replacing your existing AI logic. */
const fs=require('fs');
function read(p){return fs.readFileSync(p,'utf8')}
function write(p,s){fs.writeFileSync(p,s)}
let index=read('index.html');
if(!index.includes('app-config.js')) index=index.replace('<script src="https://unpkg.com/mammoth@1.8.0/mammoth.browser.min.js"></script>','<script src="https://unpkg.com/mammoth@1.8.0/mammoth.browser.min.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2"></script>\n<script src="app-config.js"></script>');
if(!index.includes('id="accountArea"')) index=index.replace('<div class="top-actions">','<div class="top-actions"><div id="accountArea" class="account-area"><a class="account-btn" href="auth.html">Sign in</a></div>');
index=index.replace('<span id="planBadge" class="plan free">FREE</span>','<span id="planBadge" class="plan free hidden">FREE</span>');
index=index.replace('<button id="upgradeBtn" class="primary">Upgrade to Pro</button>','<button id="upgradeBtn" class="primary hidden">Upgrade to Pro</button>');
index=index.replace('<section class="card pricing">','<section class="card pricing plans-panel hidden" id="plansPanel">');
index=index.replace('<script src="app.js"></script>','<script src="https://checkout.razorpay.com/v1/checkout.js"></script>\n<script src="app.js"></script>\n<script src="account.js"></script>');
index=index.replace(/<div id="upgradeModal"[\s\S]*?<\/div>\s*\n\s*<script src="https:\/\/cdnjs.cloudflare.com\/ajax\/libs\/pdf\.js/, '<div id="upgradeModal" class="modal hidden"><div class="modal-box"><button id="closeModal" class="modal-close">×</button><h2>CareerLab Pro</h2><p id="upgradeIntro">Unlock advanced career preparation with CareerLab Pro.</p><div class="modal-feature">✓ Advanced interview coaching</div><div class="modal-feature">✓ Sample answer suggestions</div><div class="modal-feature">✓ Project architecture</div><div class="modal-feature">✓ Resume-based job discovery</div><button id="payProBtn" class="primary full">Continue to secure payment</button><p id="paymentStatus" class="muted"></p></div></div>\n\n<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/');
write('index.html',index);
let app=read('app.js');
app=app.replace('isPro:localStorage.getItem("careerlab_plan")==="pro",interview:', 'isPro:false,plansEnabled:false,featureFlags:{},interview:');
app=app.replace('const r=await fetch(AI_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});','const token=window.careerLabGetAccessToken?await window.careerLabGetAccessToken():null;const headers={"Content-Type":"application/json"};if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(AI_ENDPOINT,{method:"POST",headers,body:JSON.stringify(body)});');
app=app.replace('if(["project","skill_gap"].includes(mode)&&!state.isPro){openUpgrade();return;}','if(state.plansEnabled&&state.featureFlags[mode]===false&&!state.isPro){openUpgrade();return;}');
app=app.replace('if(!state.isPro){$("sampleAnswer").textContent="Upgrade to CareerLab Pro for detailed answer improvement and sample answer guidance.";return;}','if(state.plansEnabled&&state.featureFlags.interview_feedback===false&&!state.isPro){openUpgrade();return;}');
app=app.replace('if(!state.isPro){openUpgrade();return;}\n  if(!state.resumeText){','if(state.plansEnabled&&state.featureFlags.job_finder===false&&!state.isPro){openUpgrade();return;}\n  if(!state.resumeText){');
app=app.replace('function openUpgrade(){$("upgradeModal").classList.remove("hidden");}','function openUpgrade(){if(!state.plansEnabled)return;if(window.careerLabRequireLogin&&!window.careerLabRequireLogin())return;$("upgradeModal").classList.remove("hidden");window.careerLabPreparePayment?.();}');
app=app.replace('function updatePlanUI(){const b=$("planBadge");b.textContent=state.isPro?"PRO":"FREE";b.className=state.isPro?"plan pro":"plan free";$("upgradeBtn").textContent=state.isPro?"Pro Active":"Upgrade to Pro";}','function updatePlanUI(){const b=$("planBadge"),u=$("upgradeBtn"),p=$("plansPanel");if(!state.plansEnabled){b?.classList.add("hidden");u?.classList.add("hidden");p?.classList.add("hidden");return}b?.classList.remove("hidden");u?.classList.remove("hidden");p?.classList.remove("hidden");if(b){b.textContent=state.isPro?"PRO":"FREE";b.className=state.isPro?"plan pro":"plan free"}if(u)u.textContent=state.isPro?"Pro Active":"Upgrade to Pro"}');
app=app.replace('function populate(){','window.careerLabApplyPlatform=function(cfg){state.plansEnabled=!!cfg?.plansEnabled;state.featureFlags=cfg?.features||{};state.isPro=!!cfg?.isPro;updatePlanUI()};window.careerLabSetPlan=function(v){state.isPro=!!v;updatePlanUI()};function populate(){');
app=app.replace('$("activateTestPro").addEventListener("click",activateTestPro);','$("payProBtn")?.addEventListener("click",()=>window.careerLabStartPayment?.());');
write('app.js',app);
let css=read('styles.css');
css += '\n.hidden{display:none!important}.account-area{display:flex;align-items:center;gap:7px}.account-btn,.account-menu-btn{display:inline-flex;align-items:center;justify-content:center;padding:9px 12px;border-radius:10px;border:1px solid var(--border);background:var(--soft);color:var(--text);text-decoration:none;font-size:12px;font-weight:800}.account-user{display:flex;align-items:center;gap:8px;padding:5px 7px 5px 10px;border:1px solid var(--border);border-radius:12px;background:var(--soft);font-size:12px}.account-avatar{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:var(--primary);color:#fff;font-weight:900}.account-links{display:flex;gap:6px;align-items:center}.auth-page{min-height:100vh;display:grid;place-items:center;padding:30px}.auth-card{width:min(520px,100%);background:var(--card);border:1px solid var(--border);border-radius:22px;padding:30px;box-shadow:var(--shadow)}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0}.auth-tab{background:var(--soft);color:var(--text);border:1px solid var(--border)}.auth-tab.active{background:var(--primary);color:#fff}.auth-divider{display:flex;align-items:center;gap:10px;margin:18px 0;color:var(--muted);font-size:12px}.auth-divider:before,.auth-divider:after{content:"";height:1px;background:var(--border);flex:1}.social-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.auth-message{min-height:24px;margin:12px 0;font-size:13px}.auth-message.error{color:var(--danger)}.auth-message.ok{color:var(--success)}.admin-layout{width:min(1100px,92%);margin:0 auto;padding:30px 0 70px}.admin-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.admin-card{background:var(--card);border:1px solid var(--border);border-radius:18px;padding:22px;box-shadow:var(--shadow)}.toggle-row{display:flex;align-items:center;justify-content:space-between;gap:15px;padding:13px 0;border-bottom:1px solid var(--border)}.toggle{width:48px;height:28px;border-radius:999px;background:#cfd5df;position:relative;padding:0}.toggle:after{content:"";position:absolute;width:22px;height:22px;left:3px;top:3px;background:#fff;border-radius:50%;transition:.2s}.toggle.on{background:var(--primary)}.toggle.on:after{left:23px}.admin-stat-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.admin-stat{padding:16px;border:1px solid var(--border);border-radius:14px;background:var(--soft)}.admin-stat strong{font-size:24px;display:block}@media(max-width:700px){.admin-grid,.admin-stat-grid,.social-grid{grid-template-columns:1fr}}\n';
write('styles.css',css);
console.log('Patched index.html, app.js and styles.css.');
