const C=window.CAREERLAB_CONFIG||{};const supabase=window.supabase?.createClient(C.SUPABASE_URL||"",C.SUPABASE_PUBLISHABLE_KEY||"");let signUp=false,phoneMode=false;const $=id=>document.getElementById(id);function msg(t,type=""){const e=$("authMessage");e.textContent=t;e.className="auth-message "+type}function ready(){if(!C.SUPABASE_URL||!C.SUPABASE_PUBLISHABLE_KEY){msg("Add your Supabase URL and publishable key in app-config.js.","error");return false}return true}async function oauth(provider){if(!ready())return;const{error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:location.origin+"/index.html"}});if(error)msg(error.message,"error")}
$("signInTab").onclick=()=>{signUp=false;phoneMode=false;$("signInTab").classList.add("active");$("signUpTab").classList.remove("active");$("phoneTab").classList.remove("active");$("authForm").classList.remove("hidden");$("phonePanel").classList.add("hidden");$("nameWrap").classList.add("hidden");$("emailSubmit").textContent="Sign in"};
$("signUpTab").onclick=()=>{signUp=true;phoneMode=false;$("signUpTab").classList.add("active");$("signInTab").classList.remove("active");$("phoneTab").classList.remove("active");$("authForm").classList.remove("hidden");$("phonePanel").classList.add("hidden");$("nameWrap").classList.remove("hidden");$("emailSubmit").textContent="Create account"};
$("phoneTab").onclick=()=>{phoneMode=true;$("phoneTab").classList.add("active");$("signInTab").classList.remove("active");$("signUpTab").classList.remove("active");$("authForm").classList.add("hidden");$("phonePanel").classList.remove("hidden")};
$("authForm").onsubmit=async e=>{e.preventDefault();if(!ready())return;const email=$("authEmail").value.trim(),password=$("authPassword").value,name=$("authName").value.trim();let r;if(signUp)r=await supabase.auth.signUp({email,password,options:{data:{display_name:name},emailRedirectTo:location.origin+"/index.html"}});else r=await supabase.auth.signInWithPassword({email,password});if(r.error)return msg(r.error.message,"error");msg(signUp?(r.data.session?"Account created. Redirecting…":"Check your email to confirm your account."):"Signed in. Redirecting…","ok");if(r.data.session)setTimeout(()=>location.href=new URLSearchParams(location.search).get("next")||"index.html",500)};
$("sendOtpBtn").onclick=async()=>{if(!ready())return;const phone=$("phoneNumber").value.trim();if(!phone)return msg("Enter your phone number with country code.","error");const{error}=await supabase.auth.signInWithOtp({phone});if(error)msg(error.message,"error");else{$("otpWrap").classList.remove("hidden");msg("OTP sent. Check your phone.","ok")}};
$("verifyOtpBtn").onclick=async()=>{if(!ready())return;const phone=$("phoneNumber").value.trim(),token=$("phoneOtp").value.trim();const{data,error}=await supabase.auth.verifyOtp({phone,token,type:"sms"});if(error)return msg(error.message,"error");msg("Phone verified. Redirecting…","ok");if(data.session)setTimeout(()=>location.href=new URLSearchParams(location.search).get("next")||"index.html",500)};
$("forgotBtn").onclick=async()=>{if(!ready())return;const email=$("authEmail").value.trim();if(!email)return msg("Enter your email first.","error");const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+"/auth.html?mode=recovery"});msg(error?error.message:"Password reset link sent. Check your email.",error?"error":"ok")};
$("googleBtn").onclick=()=>oauth("google");$("githubBtn").onclick=()=>oauth("github");$("microsoftBtn").onclick=()=>oauth("azure");
$("magicBtn").onclick=async()=>{if(!ready())return;const email=$("authEmail").value.trim();if(!email)return msg("Enter your email first.","error");const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+"/index.html"}});msg(error?error.message:"Magic link sent. Check your email.",error?"error":"ok")};
async function recovery(){if(location.search.includes("mode=recovery")){$("resetPanel").classList.remove("hidden");$("authTitle").textContent="Create a new password";$("authIntro").textContent="Choose a new password for your CareerLab account.";$("authForm").classList.add("hidden");$("phonePanel").classList.add("hidden");}}
$("savePasswordBtn").onclick=async()=>{if(!ready())return;const p=$("newPassword").value;if(p.length<8)return msg("Use at least 8 characters.","error");const{error}=await supabase.auth.updateUser({password:p});if(error)return msg(error.message,"error");msg("Password updated. You can now sign in.","ok");setTimeout(()=>location.href="index.html",700)};recovery();
