const OWNER_EMAIL="YOUR_EMAIL@example.com";
const SITE_URL="https://aravinth-venkat.github.io";
const SPREADSHEET_ID="";
const DRIVE_FOLDER_ID="";
function setup(){const p=PropertiesService.getScriptProperties();let ss,id=SPREADSHEET_ID||p.getProperty("SPREADSHEET_ID");if(id)ss=SpreadsheetApp.openById(id);else{ss=SpreadsheetApp.create("Aravinth Portfolio Data");p.setProperty("SPREADSHEET_ID",ss.getId())}const tabs={Visitors:["visitorId","firstSeen","lastSeen","visitCount","lastPath","ownerMode"],Events:["timestamp","visitorId","action","path","title","referrer","userAgent","screen","ownerMode"],Referrals:["timestamp","visitorId","name","email","company","type","message","fileName","fileUrl"],Questions:["timestamp","visitorId","name","email","topic","urgency","question"],Feedback:["timestamp","visitorId","name","email","rating","comment"],Challenges:["timestamp","roomId","visitorId","name","email","status","page","createdAt","joinedAt"],Rooms:["roomId","createdAt","updatedAt","fen","lastMove","history","playerWhite","playerBlack","status"],Moves:["timestamp","roomId","visitorId","move","fen","role"]};Object.keys(tabs).forEach(n=>{let s=ss.getSheetByName(n);if(!s)s=ss.insertSheet(n);if(s.getLastRow()===0)s.appendRow(tabs[n])});let fid=DRIVE_FOLDER_ID||p.getProperty("DRIVE_FOLDER_ID");if(!fid){fid=DriveApp.createFolder("Aravinth Portfolio Uploads").getId();p.setProperty("DRIVE_FOLDER_ID",fid)}p.setProperty("SPREADSHEET_ID",ss.getId());return{spreadsheetId:ss.getId(),driveFolderId:fid}}
function db_(){const p=PropertiesService.getScriptProperties(),id=SPREADSHEET_ID||p.getProperty("SPREADSHEET_ID");if(!id)throw Error("Run setup() first.");return SpreadsheetApp.openById(id)}
function out_(o,cb){const t=ContentService.createTextOutput(cb?cb+"("+JSON.stringify(o)+")":JSON.stringify(o));return t.setMimeType(cb?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
function doGet(e){const a=e.parameter.action||"health",cb=e.parameter.callback;try{if(a==="availability")return out_({ok:true,online:isOwnerOnline_()},cb);if(a==="pending_challenges")return out_({ok:true,challenges:pending_()},cb);if(a==="room")return out_(room_(e.parameter.roomId,e.parameter.role,e.parameter.visitorId),cb);return out_({ok:true,service:"Aravinth.dev backend"},cb)}catch(err){return out_({ok:false,error:String(err)},cb)}}
function doPost(e){let d={};try{d=JSON.parse(e.postData.contents||"{}")}catch(err){return out_({ok:false,error:"Invalid JSON"})}try{const a=d.action||"event";if(a==="visit"||a==="heartbeat"||a==="owner_heartbeat")visitor_(d);if(a==="referral")referral_(d);if(a==="question")question_(d);if(a==="feedback")feedback_(d);if(a==="challenge")challenge_(d);if(a==="room_create")roomCreate_(d);if(a==="room_move")roomMove_(d);event_(d);return out_({ok:true})}catch(err){return out_({ok:false,error:String(err)})}}
function visitor_(d){const s=db_().getSheetByName("Visitors"),rows=s.getDataRange().getValues(),id=String(d.visitorId||"");let r=-1;for(let i=1;i<rows.length;i++)if(String(rows[i][0])===id){r=i+1;break}const now=new Date();if(r<0)s.appendRow([id,now,now,1,d.path||"",!!d.owner]);else s.getRange(r,3,1,4).setValues([[now,Number(s.getRange(r,4).getValue()||0)+1,d.path||"",!!d.owner]])}
function event_(d){db_().getSheetByName("Events").appendRow([new Date(),d.visitorId||"",d.action||"",d.path||"",d.title||"",d.referrer||"",d.userAgent||"",d.screen||"",!!d.owner])}
function referral_(d){let url="";if(d.fileData&&d.fileName){const p=PropertiesService.getScriptProperties(),f=DriveApp.getFolderById(DRIVE_FOLDER_ID||p.getProperty("DRIVE_FOLDER_ID"));url=f.createFile(Utilities.newBlob(Utilities.base64Decode(d.fileData),d.fileType||MimeType.PDF,d.fileName)).getUrl()}db_().getSheetByName("Referrals").appendRow([new Date(),d.visitorId||"",d.name||"",d.email||"",d.company||"",d.type||"",d.message||"",d.fileName||"",url]);notify_("New portfolio referral from "+(d.name||"visitor"),"Name: "+d.name+"\nEmail: "+d.email+"\nCompany: "+d.company+"\nType: "+d.type+"\n\n"+d.message+"\n\nResume: "+url)}
function question_(d){db_().getSheetByName("Questions").appendRow([new Date(),d.visitorId||"",d.name||"",d.email||"",d.topic||"",d.urgency||"",d.question||""]);notify_("New ServiceNow question from "+(d.name||"visitor"),"Email: "+d.email+"\nTopic: "+d.topic+"\nUrgency: "+d.urgency+"\n\n"+d.question)}
function feedback_(d){db_().getSheetByName("Feedback").appendRow([new Date(),d.visitorId||"",d.name||"",d.email||"",d.rating||"",d.comment||""])}
function challenge_(d){const room=d.roomId||"ARV-"+Utilities.getUuid().slice(0,8).toUpperCase(),s=db_().getSheetByName("Challenges");s.appendRow([new Date(),room,d.visitorId||"",d.name||"",d.email||"","pending",d.page||"",new Date(),""]);notify_("♟ New chess challenge for Aravinth","Player: "+d.name+"\nEmail: "+d.email+"\nRoom: "+room+"\nOpen: "+SITE_URL+"/chess.html?owner=1&room="+room)}
function roomCreate_(d){const s=db_().getSheetByName("Rooms"),rows=s.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][0])===String(d.roomId))return;s.appendRow([d.roomId,new Date(),new Date(),d.fen||"","","",d.visitorId||"","","waiting"])}
function room_(id,role,vid){const s=db_().getSheetByName("Rooms"),rows=s.getDataRange().getValues();let x=null,r=-1;for(let i=1;i<rows.length;i++)if(String(rows[i][0])===String(id)){x=rows[i];r=i+1;break}if(!x)return{ok:false};if(role==="admin"&&x[8]==="waiting"){s.getRange(r,9).setValue("active");s.getRange(r,8).setValue(vid||"");markJoined_(id)}return{ok:true,roomId:x[0],fen:x[3],lastMove:x[4],history:String(x[5]||"").split("|").filter(Boolean),status:s.getRange(r,9).getValue()||"waiting",role:role||"player"}}
function markJoined_(id){const s=db_().getSheetByName("Challenges"),rows=s.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][1])===String(id)&&String(rows[i][5])==="pending"){s.getRange(i+1,6).setValue("active");s.getRange(i+1,9).setValue(new Date());break}}
function pending_(){const s=db_().getSheetByName("Challenges"),rows=s.getDataRange().getValues(),out=[];for(let i=1;i<rows.length;i++)if(String(rows[i][5])==="pending")out.push({roomId:rows[i][1],name:rows[i][3],email:rows[i][4],createdAt:rows[i][7]});return out}
function roomMove_(d){const s=db_().getSheetByName("Rooms"),rows=s.getDataRange().getValues();for(let i=1;i<rows.length;i++)if(String(rows[i][0])===String(d.roomId)){const r=i+1,h=String(rows[i][5]||""),next=h?(h+"|"+d.move):d.move;s.getRange(r,3,1,4).setValues([[new Date(),d.fen||"",d.move||"",next]]);db_().getSheetByName("Moves").appendRow([new Date(),d.roomId||"",d.visitorId||"",d.move||"",d.fen||"",d.role||""]);break}}
function isOwnerOnline_(){const s=db_().getSheetByName("Visitors"),rows=s.getDataRange().getValues(),cut=Date.now()-90000;for(let i=1;i<rows.length;i++)if((rows[i][5]===true||rows[i][5]==="true")&&rows[i][2]&&new Date(rows[i][2]).getTime()>cut)return true;return false}
function notify_(subject,body){if(OWNER_EMAIL&&OWNER_EMAIL.indexOf("@")>0)MailApp.sendEmail(OWNER_EMAIL,subject,body)}
